# ----------------------------------------------------------------------
# |
# |  Copyright (c) 2024 David Brownell
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "Standard"

run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Once a day at 12am UTC
  workflow_dispatch:

jobs:
  # ----------------------------------------------------------------------
  action_contexts:
    name: "Display GitHub Action Contexts"
    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_display_action_contexts.yaml@CI-v0.15.2

  # ----------------------------------------------------------------------
  validate:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python.yaml@CI-v0.15.2
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  package_coverage:
    needs: validate

    name: Postprocess Coverage Info
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_package_python_coverage.yaml@CI-v0.15.2
    with:
      gist_id: 4065d22fd6323840e81951a3bd271e1c
      gist_filename: TheLanguage1_coverage.json
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

  # ----------------------------------------------------------------------
  create_package:
    needs: validate

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Create Package

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_package.yaml@CI-v0.15.2
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  validate_package:
    needs: create_package

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate Package

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_package.yaml@CI-v0.15.2
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      validation_command: python -c "from TheLanguage1 import __version__; print(__version__)"

  # TODO: # ----------------------------------------------------------------------
  # TODO: create_binary:
  # TODO:   needs: validate
  # TODO:
  # TODO:   strategy:
  # TODO:     fail-fast: false
  # TODO:
  # TODO:     matrix:
  # TODO:       os:
  # TODO:         - macos-latest
  # TODO:         - ubuntu-latest
  # TODO:         - windows-latest
  # TODO:
  # TODO:       python_version:
  # TODO:         - "3.11"
  # TODO:
  # TODO:   name: Create Binary
  # TODO:
  # TODO:   uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_binary.yaml@CI-v0.15.2
  # TODO:   with:
  # TODO:     operating_system: ${{ matrix.os }}
  # TODO:     python_version: ${{ matrix.python_version }}
  # TODO:
  # TODO: # ----------------------------------------------------------------------
  # TODO: validate_binary:
  # TODO:   needs: create_binary
  # TODO:
  # TODO:   strategy:
  # TODO:     fail-fast: false
  # TODO:
  # TODO:     matrix:
  # TODO:       os:
  # TODO:         - macos-latest
  # TODO:         - ubuntu-latest
  # TODO:         - windows-latest
  # TODO:
  # TODO:       python_version:
  # TODO:         - "3.11"
  # TODO:
  # TODO:   name: Validate Binary
  # TODO:
  # TODO:   uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_binary.yaml@CI-v0.15.2
  # TODO:   with:
  # TODO:     operating_system: ${{ matrix.os }}
  # TODO:     python_version: ${{ matrix.python_version }}
  # TODO:     validation_command: TheLanguage1 Version



  # ----------------------------------------------------------------------
  publish:
    needs:
      - validate_package
      # TODO: - validate_binary


    name: Publish

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_publish_python.yaml@CI-v0.15.2
    with:
      release_sources_configuration_filename: .github/release_sources.yaml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
